### PR TITLE
6.x equations and extra DOIs in bibliography

### PR DESCRIPTION
**Pull request by pwep**
Fixing some of the longer equations in in 6.x, and adding DOIs to references cited in early chapters.

### CODE REVIEW

**Comment by dpc10ster** [comment]
Thanks Peter; Dev

**Comment by dpc10ster** [comment]
Hi Peter,

Sorry for the long email, but I am stuck. I just pushed my code.

Dev

Having problems referencing a table in a previous chapter. This was the
initial error message.

Output created: docs/RJafrocBook.pdf
> Warning message:
> LaTeX Warning: Reference `tab:ratingsParadigmTable1' on page 77 undefined
> on input line 2003.


* The table is labeled in 04-ratings-paradigm at line 48
* It is referenced in 06-binormal-model at line 558

As per https://bookdown.org/yihui/rmarkdown-cookbook/cross-ref.html:
* I updated index.Rmd as follows:
* output:
   + bookdown::html_document2: default
   + bookdown::pdf_document2: default

New error message:

> A new version of TeX Live has been released. If you need to install or
> update any LaTeX packages, you have to upgrade TinyTeX with
> tinytex::reinstall_tinytex(). If it fails to upgrade, you might be using a
> default random CTAN mirror that has not been fully synced to the main CTAN
> repository, and you need to wait for a few more days or use a CTAN mirror
> that is known to be up-to-date (see the "repository" argument on the help
> page ?tinytex::install_tinytex()).
> ! Package inputenc Error: Unicode character ≥ (U+2265)
> (inputenc)                not set up for use with LaTeX.
> Try other LaTeX engines instead (e.g., xelatex) if you are using pdflatex.
> See https://bookdown.org/yihui/rmarkdown-cookbook/latex-unicode.html
> Error: LaTeX failed to compile RJafrocBook.tex. See
> https://yihui.org/tinytex/r/#debugging for debugging tips. See
> RJafrocBook.log for more info.
> Execution halted
> Exited with status 1.



I updated TinyTex (long update) and build pdf using pdf_document2;

Still get error:

! Package inputenc Error: Unicode character ≥ (U+2265)
> (inputenc) not set up for use with LaTeX.
> Try other LaTeX engines instead (e.g., xelatex) if you are using pdflatex.
> See https://bookdown.org/yihui/rmarkdown-cookbook/latex-unicode.html
> Error: LaTeX failed to compile RJafrocBook.tex. See
> https://yihui.org/tinytex/r/#debugging for debugging tips. See
> RJafrocBook.log for more info.
> Execution halted
> Exited with status 1.

**Comment by pwep** [comment]
Hi Dev - I'll take a look.

It looks like this line...

https://github.com/dpc10ster/RJafrocBook/blob/c216212410feec20c030606574f9f49d819d2050/03-modeling-binary-task.Rmd#L21

..has got a greater-or-equals unicode character which could be the source of the error. It needs to be replaced with the latex equivalent (\geq).

I'll take a closure look in the next few hours.

**Comment by dpc10ster** [comment]
Our emails crossed; I implemented the fix you suggested below.

**Pull request merged**
